gtk-rs/glib

.travis.yml

cc https://github.com/rust-gnome/gtk/issues/50

Make travis build the examples repo to check for intercrate breakage

---

.travis.yml

Now that we've attained beta compatibility let's keep it that way :)

Travis: build on both nightly and beta

---

src/error.rs

Implemented Debug, Display, and Error for glib::Error

---

src/date.rs

I expect the tests to be green now.

Fix Date on Windows

---

src/object.rs

Remove compilation warning

---

src/value.rs

Mark Value bindings as unsafe

---

src/date.rs
src/error.rs
src/lib.rs
src/permission.rs
src/source.rs
src/value.rs

Remove part of rustdoc comments

---

src/app_info.rs
src/lib.rs
src/object.rs

This name seems more appropriate for a marker trait

Rename `Upcast` to `IsA`

---

src/lib.rs
src/object.rs

Add documentation

---

src/translate.rs

On unix this allows arbitrary encodings, otherwise (windows) UTF-8 is expected.

Implement conversions between `char*` and `Path[Buf]`

---

appveyor.yml
src/lib.rs
src/object.rs
src/prelude.rs
src/shared.rs
src/value.rs
src/variant.rs
src/variant_type.rs

I'm somewhat open to suggestions of alternative names for the `VariantType`/`VariantTy` pair.
There's some scarily unsafe stuff there. I might need to add more comments explaining why I think it's sound.

Add limited Variant binding

---

src/signal.rs

We need `Inhibit` in other crates, see https://github.com/gtk-rs/gio/blob/master/Gir.toml#L53-L59

Add signal::Inhibit

---

Cargo.toml

Update crates.io version

---

src/types.rs

Fix little typo

---

src/boxed.rs
src/object.rs
src/shared.rs
src/translate.rs
src/variant_type.rs

Part of https://github.com/gtk-rs/gdk/issues/136

Split FromGlibPtr trait

---

src/translate.rs

Fixes errors found in https://github.com/gtk-rs/gtk/pull/478

Fix FromGlibPtrContainer implementations

---

src/translate.rs

Minor optimization `ToGlibPtr` for slices

Replace `g_list_reverse` with `rev`

---

src/object.rs

This is useful for using properties (or properties of types) that are
not part of any bindings in a still safe way.

Implement public ObjectExt::set_property() and ::get_property()

---

src/object.rs

Implement public ObjectExt::get_property_type()

---

src/translate.rs

Add ToGlibContainerFromSlice impls for *const GList / GSList

---

src/main_context.rs
src/signal.rs
src/source.rs
src/value.rs

This reverts commit ba8b1dcb577f816b1a0c552cb300de6a8e6f5b3e.
Part of https://github.com/gtk-rs/glib/pull/250
cc @GuillaumeGomez, @sdroege

Revert "Deprecate CallbackGuard"

---

src/types.rs

I need this for some new GStreamer API :)

Implement StaticType for Type

---

Cargo.toml
src/source.rs

I took a stab at unix_fd support.  Please review.

Add unix fd support

---

src/main_context_futures.rs
src/source_futures.rs

And add a test for this, which reproduced it most of the time.

Fix logic error in futures wakeup that caused them to often not be woken up

---

src/utils.rs

Fix https://github.com/gtk-rs/glib/issues/346

make get_real_name return OsString

---

Makefile
src/gobject/auto/binding.rs

Fix regen_check

---

src/variant.rs

This is not a boxed type and we have to use specific functions for
storing/retrieving from a Value
---
CC @jsparber

variant: Implement Value traits manually

---

src/subclass/mod.rs
src/subclass/types.rs

Fixes https://github.com/gtk-rs/glib/issues/408

Add API for implementing GObject interfaces generically

---

Cargo.toml
src/translate.rs

Replace deprecated tempdir crate

---

src/lib.rs
src/prelude.rs

It's useful to have for the various API defined on it.
----
CC @EPashkin @GuillaumeGomez

Add ObjectType trait to prelude

---

Gir.toml
src/byte_array.rs
src/lib.rs

Not exactly the most useful thing, but an interesting exercise during
Rust+GNOME hackfest :)
(The gir definitions were a bit too weird to auto-generate a satisfying binding)
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>

Add ByteArray binding

---

src/time_val.rs

Add missing traits

---

src/byte_array.rs
src/main_context.rs
src/signal.rs
src/subclass/boxed.rs
src/subclass/types.rs
src/translate.rs
src/value_array.rs

Move trampolines

---

src/boxed.rs
src/clone.rs

I was a bit too aggressive in #539, sorry...
Also take this opportunity to run fmt which should fix some CI jobs.

Remove unneeded `allow(clippy::missing_safety_doc)` attributes (538)

---

src/enums.rs
src/gstring.rs
src/object.rs
src/value.rs

Implement Send/Sync for more types where it's correct

---

src/clone.rs

More compilation errors for clone macro

---

.travis.yml

Add checks for gtk4

---

src/translate.rs

Needed for creating bindings of the NetworkManager client library which heavily relies on GPtrArray.
This is the PtrArray part of #482 and was taken directly from there. On top of it I run `cargo fmt`.
Tested with a modified gir that includes PtrArray. Going to PR that part as well once PtrArray is included in glib.

Add PtrArray and related trait implementations

---

src/clone.rs

Allow to specify type for closure arguments

---

src/translate.rs

Attempts to solve https://github.com/gtk-rs/glib/issues/586

translate: Clarify the purpose and the effect of translation traits

---

.travis.yml

I can't really make the build simpler considering that all rust version and platforms kinda have unique things to run. It's kind of a mess so I won't touch for the moment. :)
cc @EPashkin @sdroege

Add manual traits check

---

src/translate.rs

@GuillaumeGomez @EPashkin 
See individual commits. I tried splitting it up as much as possible to make it easier to review. This is also a candidate for a new bugfix release.

Various container translation cleanups/fixes

---

src/closure.rs
src/main_context_channel.rs
src/main_context_futures.rs

See individual commits.
@GuillaumeGomez @EPashkin

Remove some unneeded mem::forget() calls and Option wrappers

---

src/log.rs
tests/log.rs
tests/print.rs

We first need to fix https://github.com/gtk-rs/glib/issues/616.

Clean up log functions

---

clone_tests/clone_compilation_errors.py
src/clone.rs

Improve clone! error messages

---

src/log.rs

Improve log macros

---

clone_tests/clone_compilation_errors.py
src/clone.rs

Fixes https://github.com/gtk-rs/glib/issues/615.
Once this one is merged, I'll migrate the whole clone macro into a proc-macro because it's really becoming a mess...

Add @weak-allow-none for clone macro

---

src/byte_array.rs
src/translate.rs
src/value.rs
src/variant.rs

Was fixing some clippy warnings and end up finding an actual bug. :)

Fix variant PartialOrd

---

src/lib.rs
src/variant.rs
src/variant_dict.rs

This is the first step along the path to resolving https://github.com/gtk-rs/gio/issues/291

VariantDict support

---

glib-macros/src/gboxed_derive.rs
glib-macros/tests/test.rs

CC @gdesmott @GuillaumeGomez @EPashkin

Only derive SetValueOptional for nullable GBoxed types

---

src/object.rs
src/subclass/object.rs

Also improve errors messages everywhere.
CC @EPashkin @GuillaumeGomez

Various improvements to property handling

---

glib-macros/src/genum_derive.rs
glib-macros/src/gflags_attribute.rs

CC @gdesmott @GuillaumeGomez @EPashkin @MathieuDuponchelle

Don't require users of the glib proc macros to have gobject_sys in scope

---

src/object.rs

This was done elsewhere in #522.

Use $crate when invoking glib_object_wrapper! in a macro

---

src/param_spec.rs

Borrow some values from ParamSpec instead of copying

---

src/lib.rs
src/object.rs
src/param_spec.rs
src/prelude.rs

Improve ParamSpec bindings

---

src/object.rs

This makes it clearer that the memory is actually pinned and must not be
moved, and especially makes it only possible to move with unsafe
functions.

Use Pin<Box<GWeakRef>> for storing weak references

---

src/time_val.rs

Needed by https://github.com/gtk-rs/gdk-pixbuf/pull/158
cc @sdroege

Add missing ToGlibPtr implementation

---

Cargo.toml
src/closure.rs
src/lib.rs
src/object.rs
src/value.rs

Remove ToValue impl for Value, and various other related cleanups
