COPYRIGHT, Cargo.toml, LGPL, glib-sys/Cargo.toml, src/lib.rs
Here're the proposed changes to the license header and various copyright-related things in this and sibling repos.
* Change the license headers.
* Put the list of authors into COPYRIGHT and remove it from Cargo.toml.
* Add the text of LGPL for reference.
For now, only `src/lib.rs` header is changed, after agreeing on the final version of the text I'll put it in other files too.
=> Add COPYRIGHT and change license headers in the source files

src/signal.rs
It's named incorrectly and seems to be GTK-specific.
=> signals: Remove struct Propagate

glib-sys/src/lib.rs, src/app_info.rs, src/lib.rs, src/object.rs, src/translate.rs
This can come in early, no need to wait for GTK to be finished.
Also some glib improvements (populate `ObjectExt` and `AppInfoExt`) could be done independently.
=> Some Object tweaks and struct GAppInfo

glib-sys/src/lib.rs
This commit introduces the native bindings for GHashTable.
Some functions have been omitted, namely the ones taking an "unsafe
extern "c" fn" as an argument, and those dealing with GHashTableIter.
Also added a rudimentary test case.
I can also try to implement the corresponding interface in the main glib crate (although, I'm not really sure how stable the HashMap API really is).
=> ffi bindings for GHashTable

src/lib.rs, src/object.rs
Remove `Upcast::upcast` making it a marker trait.
`Downcast` is not considered a general purpose trait, it's an implementation detail now.
=> Create `trait Cast` with generic `upcast` and `downcast` methods

src/lib.rs, src/types.rs, src/value.rs, src/wrapper.rs
Here's the best compromise between type safety and ergonomics I've managed to achieve.
cc #73 
Examples:
```rust
let mut value = glib::Value::from(Some("Hello world !"));
println!("gvalue.get example: {}", value.typed::<String>().unwrap().get().unwrap());
let mut int = glib::Value::from(1);
int.typed_mut::<i32>().unwrap().set_some(&2);
assert_eq!(int.get(), Some(2));
for i in 0..10 {
let iter = right_store.append(None);
right_store.set_value(&iter, 0, &i.into());
}
```
=> Overhaul `GValue` bindings

Cargo.toml
Implement the reinstatement of version features outlined in https://github.com/gtk-rs/gtk/issues/243.
- Installed library version detection no longer impacts conditional compilation.
- Each crate defaults to supporting a particular minimal upstream version.
- Higher (newer) versions need to be enabled via cargo features e.g. `--features 3.16`, `features = ["3.16"]`.
- The selected version is checked against `pkg-config` aborting the build if it's too high.
- The use of `pkg-config` can be overridden by setting `GTK_LIB_DIR` env variable, which translates into `-L $GTK_LIB_DIR` linker argument. No version checks are done in this case.
[breaking change]
=> Switch to version features instead of autodetection

src/source.rs
Fix warning introduced https://github.com/rust-lang/rust/issues/19925
See https://github.com/gtk-rs/gtk/issues/278
=> Cast trampolines before transmuting

src/lib.rs, src/prelude.rs, src/signal.rs
Adds the stop_emission() function. I believe the function signature and code is correct, but seems very straightforward to me, so may be wrong.
I haven't gotten this integrated into my code yet as I don't know how to get the `signal_id` or the `detail` argument yet, but I figured I'd post it now and report back once I've tried it out a bit.
=> Add stop_emission()

src/lib.rs, src/signal.rs
Closes #133. Tested working correctly with my Gattii project.
=> Add signal_handler_*block()

src/enums.rs, src/lib.rs, src/utils.rs
cc @gkoz @EPashkin 
@jo: It should fulfill your needs.
=> Add utilities functions

src/lib.rs, src/source.rs
I could do `glib::idle_add()` but not remove it, so I wrapped `glib::source_remove()`.
Actually I wonder if that one couldn't be automated, in wish case this PR would totally be wrong.
Thanks.
=> Added glib::source_remove()

src/source.rs
I forgot the standard derivce on SourceId. Which is making it harder to use.
=> Standard derive for SourceId.

src/translate.rs
Fix https://github.com/gtk-rs/gtk/issues/469
@Susurrus check this please.
=> Fix array of string full transfer

Cargo.toml, src/lib.rs
Preparation for apply https://github.com/gtk-rs/gir/pull/339
cc @GuillaumeGomez, @sdroege
=> Rewrite string consts

src/translate.rs
Revert one change from #153
Was wrong replacing g_free with g_strfreev by two reason:
1) g_strfreev frees inner string that already freed
2) g_strfreev must used only for string arrays, but this implementation for any arrays
=> Fix FromGlibContainer double freeing

src/value.rs
Needs some discussion if the lifetime parameter is good or not here. For G_TYPE_STRING the copying or not might not be that important, but I'll also have to implement this for more complex types in the future where copying is expensive.
Without the added lifetime parameter, the following would compile just fine (while it shouldn't):
```rust
let s = {
let v = Value::from("test");
assert_eq!(v.get::<&str>(), Some("test"));
v.get::<&str>()
};
assert_eq!(s, Some("test"));
```
(Note that using get::<String>() instead above still works, as it should)
=> Add support for getting a &str from a GValue without copying

src/object.rs
https://github.com/gtk-rs/gir/issues/367
=> Use g_object_ref_sink() instead of g_object_ref() everywhere

src/error.rs, src/lib.rs, src/utils.rs
https://github.com/gtk-rs/gir/issues/368
And example usage in utils::setenv(). Code generator changes come tomorrow when this is all ok.
How do you handle API changes?
=> Add glib::BoolError for use as return value of possibly failing functions returning booleans

src/utils.rs
There are equivalent functions with the _utf8() prefix on Windows, to which macros with the "normal" names are pointing.
See https://github.com/gtk-rs/glib/pull/169#issuecomment-302931512 and below
=> Add Windows implementations for g_setenv, g_getenv, g_unsetenv and g_get_current_dir

src/value.rs
There are some functions that need that in GStreamer.
=> Implement FromGlibPtrNone and FromGlibPtrFull for Value

src/closure.rs, src/lib.rs, src/value.rs
Hi.
I started to create the `Closure` type so that we can generate the code of methods taking a `GClosure` as a parameter.
This is a work in progress, but I open this pull request right now, which is working (even thought it contains a hack) so that you can comment on it.
I'll have to fix the hack for `size_of` by writing a C function to get the size of `GClosure`, unless someone has a better idea.
I think that marshallers support should be done in another pull request since I believe that doing something both safe and efficient will be non trivial.
=> Add support for gobject closures

src/lib.rs
Sorry I lost this statement when doing the rebase.
=> Add missing use for closure

src/error.rs
Allows retrieving the string by matching or constructing BoolErrors
without the from_glib() helper function
=> Make BoolError constructor public

src/object.rs
See https://github.com/gtk-rs/glib/pull/191#issuecomment-313355078
=> Remove now obsolete comment from ObjectExt::set_property()

src/object.rs
Depends on, and includes, https://github.com/gtk-rs/glib/pull/191
=> Implement ObjectExt::emit() for emitting arbitrary signals

src/boxed.rs, src/bytes.rs, src/closure.rs, src/error.rs, src/shared.rs, src/variant.rs, src/wrapper.rs
As long as a get_type() function is provided to the macro.
=> Implement StaticType and GValue traits for boxed/shared types too

src/boxed.rs, src/object.rs, src/shared.rs, src/translate.rs, src/value.rs
Instead of the original pointer, the pointer at the end of the array was
being freed.
=> Fix transfer full conversion of pointer arrays

src/error.rs
This should be thread-safe since all fields are
"primitive" types, except for the message C string, which
is immutable.
Fixes #195
=> Make glib::Error Send/Sync

src/lib.rs, src/object.rs
Another thing for which I had custom bindings in my GStreamer code.
=> Add WeakRef support to glib::Object

src/object.rs
This does all type-checking at runtime and is required because it's not
always statically known at compile-time whether an object implements an
interface or not.
Also add notes about this limitation to Cast::downcast() and Cast::upcast().
And change Cast::is() to only perform runtime checking. It was always
doing runtime checking anyway, but in addition did compile-time checking
which is more restricted. If compile-time checking is wanted in
addition, Downcast::can_downcast() can be used for the old behaviour.
https://github.com/gtk-rs/glib/issues/205
=> Add Cast::dynamic_cast()

src/enums.rs, src/lib.rs
=> Some helper API to dynamically work with GLib enums/flags

src/object.rs
When setting an `Object` property with a valid name but an invalid type, `"Invalid property name"` is returned. This modification allows returning `"Invalid property type"` in this case.
Changes return type for `Object::has_property`.
=> Be more precise when setting a property with invalid type

Cargo.toml
This bug comes from my script which had glib defined twice in the crate list and so updated the crate's version twice as well... Just figured this out.
=> Fix crates version

Cargo.toml, Gir.toml, src/auto/enums.rs
See https://github.com/gtk-rs/glib/pull/226#discussion_r136460029
@GuillaumeGomez, @sdroege
=> Add version for Sha384

src/lib.rs, src/object.rs, src/signal.rs, src/source.rs
commit b6ba3c6e23c638f1271efa6971646620bb2b4df9 (HEAD -> signal-handler-newtype)
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Thu Sep 7 19:55:40 2017 +0300
Don't implement Copy/Clone for SignalHandlerId and SourceId
These can only really be used once.
commit 3bfe7525982c41adab0ab7ccd584db4f674b4c3d
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Thu Sep 7 19:53:11 2017 +0300
Use a newtype wrapper around the signal handler IDs
Fixes https://github.com/gtk-rs/glib/issues/229
=> Use a newtype wrapper around the signal handler IDs

src/closure.rs, src/object.rs, src/value.rs
Fixes https://github.com/gtk-rs/glib/issues/223 and https://github.com/gtk-rs/glib/issues/228
=> Value usage improvements

src/object.rs, src/signal.rs
Namely:
- Make all the Signal related APIs usable as Object methods
- Fix signal_handler_(un)block arguments
=> Some fixes in the Signals handling

src/object.rs, src/wrapper.rs
This goes along with https://github.com/gtk-rs/gir/pull/459
I'm not 100% sure if this works yet, as my gtk module doesn't build (but glib builds).  Consider it as a proof of concept for now.
=> Allow specifying class struct to glib_wrapper!() macro

src/value.rs
It allows replacing the underlying Value inside the TypedValue with one
of a different type and breaks type-safety:
let mut meh: TypedValue<i32> = (&123i32).into();
let meh2: Value = (&1u8).to_value();
*meh = meh2;
Fixes https://github.com/gtk-rs/glib/issues/254
Also includes some trivial cleanup.
=> Don't implement DerefMut on TypedValue

src/object.rs
Otherwise it is possible, in safe code, to implement IsA<_> between
incompatible types and cause all kinds of bugs.
Fixes https://github.com/gtk-rs/glib/issues/246
=> Mark the IsA<_> trait unsafe

src/lib.rs, src/prelude.rs, src/value.rs
This is a wrapper around Value that ensures that only Send types are
stored inside it, and as such also implements Send itself. Value does
not implement Send anymore.
Fixes https://github.com/gtk-rs/glib/issues/253
What is missing now is to let `gir` emit `SendValue` instead of value if the context it appears in is `Send`
=> Implement SendValue and make Value not implement Send

src/value.rs
See commit messages. Some convenience API
=> Minor AnyValue improvements

src/value.rs
In all other places we treat NULL as an empty array instead of
considering the type to be nullable, do the same here.
=> Implement Value traits for Vec<String> more consistently

src/enums.rs, src/object.rs, src/types.rs, src/value.rs
This is only allowed for types that can be stored in GValues and
otherwise panics. The returned value contains the empty/default value of
the corresponding type.
As suggested by @EPashkin here: https://github.com/gtk-rs/gir/pull/496#issuecomment-347242579
This could be used by GIR for all the property getters to initialize the value
=> Add Value::from_type() to initialize an empty value from a Type

.travis.yml, Cargo.toml, src/translate.rs
See commit messages for details.
The first is effectively not changing anything other than adding comments in the code, using expect() instead of unwrap() with more details, and not lossy converting non-UTF8 paths from GLib to Rust on Windows but fail instead on invalid UTF-8 (otherwise we might access the wrong file! potential data loss, etc, and it's a bug in the C library if that ever happens)
=> Various Path FFI improvements

src/value.rs
Before GLib 2.48 this caused critical warnings, see
https://bugzilla.gnome.org/show_bug.cgi?id=755766
This should for real fix the warnings on travis.
=> Don't call g_value_unset() on zeroed GValues

src/bytes.rs
See individual commit messages
=> Allow creating Bytes from any AsRef<[u8]> by copying or taking ownership of it

Gir.toml, src/auto/enums.rs, src/auto/mod.rs, src/translate.rs
Part of https://github.com/gtk-rs/glib/pull/249
Also include `GLib.SeekType` for future `gio.Seekable` generation.
cc @GuillaumeGomez , @sdroege
=> Const override

src/char.rs
Also add correct casts to the UChar tests while we're at it.
Fixes https://github.com/gtk-rs/glib/issues/284
=> Fix Char tests on platforms where c_char is u8 instead of i8

Gir.toml, src/auto/key_file.rs, src/key_file.rs
It always return string https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html#g-key-file-to-data. Also it return normall null-terminated string so `length` unneeded.
cc @GuillaumeGomez, @sdroege 
Based on #286
=>  Simplify KeyFile::to_data 

src/signal.rs, src/source.rs
While 0 is never a valid SourceId, it is also not valid to use it with
any functions that work on SourceIds. It causes assertions at runtime.
The pattern of having a "non-existing" SourceId is better suited by
using an Option, and once NonZero is stabilized this can even be done
without introducing any memory overhead.
=> Remove Default impl for SourceId

src/main_context.rs, src/signal.rs, src/source.rs, src/value.rs
Part of https://github.com/gtk-rs/glib/pull/250
cc @GuillaumeGomez
=> Deprecate CallbackGuard

src/object.rs
Provide a wrapper around GWeakRef that can be safely transferred and
shared with other threads. Weak references containing types that are
Sync can be safely upgraded across different threads. In all other cases
this could potentially lead to thread safety issues. Introduce a dynamic
check that validates that upgrade operation is performed on the correct
thread.
=> Implement Sync and Send traits for all weak references.

src/object.rs
See https://github.com/gtk-rs/glib/pull/308, extends that PR.
@tmiasko @GuillaumeGomez
=> Improve set/get_property validity checks and allow to set properties from values that are a subtype of the property type

src/boxed.rs, src/shared.rs
This allows the compiler to optimize better, and in our case these
pointers are guaranteed to be not NULL.
Requires Rust 1.25. We might want to do the same for Stash maybe, or even the translation traits. But that's far more intrusive.
=> Use ptr::NonNull for Boxed/Shared wrappers

Gir.toml, src/auto/main_context.rs, src/main_context.rs
The default main context is always available and non-null. Also run
test in a new separate context to avoid interference between tests.
=> Mark g_main_context_default as non-nullable.

Gir.toml, src/auto/functions.rs
These should all use RawFd, if useful at all from Rust. It's unsafe to
call any of these functions on arbitrary integers.
=> Remove some functions that operate on raw i32 fds

Cargo.toml, src/lib.rs, src/main_context_futures.rs, src/source.rs, src/source_futures.rs
This Executor will also be used in GIO later for Futures around the async operations (and GSources)
=> Add a Futures Executor around MainContext and various Future/Stream implementations

Gir.toml, src/auto/main_loop.rs, src/main_context.rs
=> Provide panic-safe way to change thread default context.

src/source.rs
Avoid defining RawFd twice when feature v2_36 is enabled.
=> Fix cfg attribute for RawFd.

Cargo.toml, src/lib.rs, src/main_context_futures.rs
This allows using async-await when enabled, but requires nightly for now.
=> Add a new futures-nightly feature that uses futures-stable

src/lib.rs, src/string.rs
C API follows chaining pattern which is replicated in Rust version as
well. It is manually written instead of being auto-generated to avoid
unnecessary copies (generator doesn't know that the same thing is being
returned back as was provided to a function as a mutable argument).
=> Provide manual bindings for GString.

src/object.rs
Fix clippy for gtk.  Ex. see https://github.com/gtk-rs/gtk/pull/660#issuecomment-387564436
Strange for me but macro for shared and boxed don't produce warning.
@GuillaumeGomez, @sdroege
=> Ignore false clippy warning cast_ptr_alignment

src/variant_type.rs
This PR enables wrapping a ```VariantTy(pe)``` in ```Value```
=> add To/FromValue trait to VariantType

src/main_context.rs, src/signal.rs, src/source.rs, src/translate.rs
=> Fix clippy warnings

src/lib.rs, src/value_array.rs
Can't be autogenerated because all the functions return the array itself, and because it's `from_glib_none` each function would create a copy of the whole array.
Also manually added the `Deref` impls, very useful
=> Add ValueArray bindings

src/types.rs
Just for the sake of completeness
=> Implement StaticType for &mut T in addition to the existing &T

src/object.rs, src/value.rs
=> Add downcast_ref() and similar functions for all the casting machinery

src/lib.rs, src/object.rs
See https://github.com/gtk-rs/glib/pull/310#issuecomment-407688940 for discussion
=> Add new SendWeakRef type

src/boxed.rs, src/closure.rs, src/date.rs, src/error.rs, src/object.rs, src/param_spec.rs, src/shared.rs, src/string.rs, src/value_array.rs, src/variant.rs
This is still WIP and requires changes to gir that I'm currently working on.
Comments about various parts below
This is to solve https://github.com/gtk-rs/glib/issues/247 and generally improve our deriving story.
=> Various changes to how we automatically derive trait impls for boxed/shared types

src/lib.rs, src/object.rs, src/send_unique.rs
This allows sending reference counted objects to different threads as
long as only a single reference to the object exists.
----
See here for an example usage: https://github.com/sdroege/gstreamer-rs/blob/e8db89464ed51148a710d54c9969e076f3aba702/examples/src/bin/pango-cairo.rs
I plan to add this as another "concurrency" mode to gir, and then most of GIO can be Send-able via this. For Pango this is unfortunately not the case as the layout has a reference to the context (and the context to the fontmap) and uses those, so the refcount of the layout itself is not sufficient for sendability.
That is, this needs very careful investigation for enabling on reference counted objects.
=> Implement SendUniqueCell and corresponding SendUnique trait

Cargo.toml, src/lib.rs, src/main_context_futures.rs
futures 0.2 is not maintained anymore and the nightly parts don't work
anymore with latest nightly toolchain
----
If I understand how to optionally depend (based on a feature flag) on futures 0.3, I'll re-add this in a different way.
Does someone know how that would look like in `Cargo.toml`?
=> Remove futures-nightly feature

Gir.toml, src/auto/date_time.rs, src/send_unique.rs
It's immutable and all "modification" functions return a new instance.
=> Mark DateTime as Send+Send

src/subclass/boxed.rs, src/subclass/mod.rs
We might want to add more things at a later time than the get_type()
function, and it's also called like the trait in case of ObjectSubclass
=> Rename glib_boxed_get_type! to glib_boxed_type! for consistency

src/translate.rs
Part of https://github.com/gtk-rs/gtk/issues/743.
=> Replace unwrap calls with "more explicit" expect

src/gstring.rs
Needed for https://github.com/gtk-rs/gio/pull/177
=> gstring: Specify a lifetime for the From<str> impl

src/subclass/mod.rs, src/subclass/object.rs
Instead pass it from the outside into the closure.
Fixes https://github.com/gtk-rs/glib/issues/407
=> Don't duplicate property name in subclass::Property type

src/gstring.rs
`c_char` on aarch64 is a `u8`.
=> Fixes compilation on aarch64

src/subclass/types.rs
We either require new() or new_with_type() to be implemented. Making it
mandatory to implement new() in any case causes ugly code in subclasses
that only want to implement new_with_type().
----
This has the negative side-effect that there's no compiler warning if neither is implemented... but users will notice very fast because their code just does not work at all due to the `unimplemented!()` default implementation.
Compared to ugly code like [this](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/blob/fb741f26f3bef6a3ae84549a69a477273cbd8454/gst-plugin-tutorial/src/identity.rs#L165-173) I really prefer that.
=> Make ObjectType::new() optional too

src/error.rs, src/lib.rs, src/object.rs, src/utils.rs
`BoolError` can currently only be built from a `&'static str`.
This prevents the user from dynamically building the message.
Thanks to @sdroege for [suggesting to use `Cow`](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/merge_requests/196#note_98010).
It's also an opportunity to keep track of the location where the error was built.
This causes breaking changes in some callers but I think previous implementation was not future-proof, so the change should be done IMHO.
=> BoolError: allow owning the message

src/gstring.rs
=> GString: Avoid copy for From<GString> for String impl

src/gobject/auto/binding.rs, src/gobject/auto/mod.rs, src/object.rs, src/signal.rs, src/subclass/simple.rs, src/subclass/types.rs, src/wrapper.rs
This PR is still WIP as it also requires a corresponding [PR for gir](https://github.com/gtk-rs/gir/pull/689). The changes are
* Rename `Wrapper` trait to `ObjectType` to be more descriptive and add more useful API around it
* `glib_wrapper!` does not need FFI types for the parent classes in other crates anymore
* `Downcast` trait became `CanDowncast`, and the `Cast` trait impl was cleaned up
* Generate Rust class structs for class types in `glib_wrapper!`, and distinguish between classes and interfaces
* `IsA<_>` is cleaned up and does not require `ToGlibPtr` impls for everything anymore (that's why FFI types were needed). Instead `IsA<T>` requires `AsRef<T>`, i.e. we can always get back to a `&T` which then has all the traits we care about implemented.
* `IsA<Object>` and `ObjectType` …
=> Clean up glib_wrapper! macro and IsA<_>, Wrapper traits and their impls

src/object.rs
This is needed for subclassing
=> Implement DerefMut for class structs too

src/boxed.rs, src/object.rs, src/shared.rs
=> generate from_glib_borrow implementation for const pointers

src/lib.rs, src/object.rs, src/subclass/interface.rs, src/subclass/mod.rs, src/subclass/object.rs, src/subclass/types.rs
=> Add support for defining new interfaces and other minor things

.travis.yml, appveyor.yml
And add GTK 3.24 builds for Linux and update the minimum version to 3.14.
=> Update Travis to Ubuntu Xenial

src/main_context.rs, src/source.rs
This makes `gtk::idle_add()` and friends unnecessary now and is more general.
=> Add variants for GSource/MainContext functions without Send bound

src/main_context_channel.rs
This allows us to ensure that dropping the Receiver and its GSource will
also directly drop the closure, instead of having to wait for all
Senders to disappear too.
We have to use a mutex and a shared struct for this, and as such it
makes sense to directly implement the channel as part of this shared
struct. As the std mpsc channel internally also uses mutexes this should
not cause any considerable performance difference.
At the same time also simplify some more code and add a few more tests.
Fixes https://github.com/gtk-rs/glib/issues/454
----
CC @gdesmott this seems to work now but I'll have to write a few more tests (especially for the sync channel). Please give it a try and let me know how well it works for you. Once the Receiver or its GSource is finalized the closure should be freed …
=> Re-implement MainContext channel around a manual channel

src/lib.rs
=> Don't use deprecated ATOMIC_USIZE_INIT

.travis.yml, src/closure.rs, src/error.rs, src/file_error.rs, src/gobject/mod.rs, src/key_file.rs, src/lib.rs, src/main_context.rs, src/main_context_channel.rs, src/main_context_futures.rs, src/object.rs, src/quark.rs, src/send_unique.rs, src/signal.rs, src/source.rs, src/source_futures.rs, src/subclass/object.rs, src/subclass/types.rs, src/translate.rs, src/types.rs, src/value.rs
=> Fix some clippy warnings

src/gstring.rs, src/source.rs, src/value.rs
=> Add missing #[doc(hidden)]

Cargo.toml, src/lib.rs, src/main_context_futures.rs, src/source_futures.rs
While this requires nightly, the API is now stabilized and will become part of Rust 1.36. IMHO we should merge this now so that it can all get wider testing.
=> Port to futures 0.3

src/subclass/boxed.rs, src/subclass/types.rs
The assertion wasn't very user friendly, it deserves some explanations.
=> subclass: panic with error message when registering existing type

src/byte_array.rs, src/closure.rs, src/object.rs, src/source_futures.rs, src/translate.rs, src/value.rs, src/value_array.rs
=> Fix dyn and import warnings

src/main_context_channel.rs, src/variant.rs
The automatically derived implementation will only work if the channel's
item type is also implementing Clone, which is not required here.
Fixes https://github.com/gtk-rs/glib/issues/494
=> Manually implement Clone for Sender/SyncSender

src/boxed.rs, src/date.rs, src/wrapper.rs
These allow allocated them on our side and releasing all memory of them
again. It is needed for functions that take an out parameter and require
us to allocate the underlying object.
Fixes https://github.com/gtk-rs/glib/issues/469
=> Add init/clear function for boxed types

src/main_context_futures.rs
I'm trying to use the `MainContext` as a futures-0.1 `Executor` with the help of the futures-0.1 [compatibility layer](https://rust-lang-nursery.github.io/futures-rs/blog/2019/04/18/compatibility-layer.html).
It seems that the futures-0.3 `Spawn` needs to be implemented for a _reference_, so that's what I did (see [`0.3.0-alpha.16: futures-util/src/compat/executor.rs`](https://github.com/rust-lang-nursery/futures-rs/blob/0.3.0-alpha.16/futures-util/src/compat/executor.rs#L85)).
I can confirm that with this change I can use the main-context as a futures-0.1 executor by calling [`futures::task::SpawnExt.compat()`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/task/trait.SpawnExt.html#method.compat) on it.
Does this make sense?
=> Implement futures-0.3 `Spawn` for `&MainContext`

src/object.rs
We can't simply use g_value_dup_object() and take ownership of the new
reference as on the next opportunity it will be passed to
g_object_ref_sink() in a transfer-none context and that will
accidentally take ownership of the same reference and we get a double
unref() at a later time.
Instead use g_value_get_object(), if the object was floating call
g_object_ref_sink() to sink it and have the GValue as the one and only
owner at this point and then get a new reference for ourselves.
See https://gitlab.gnome.org/GNOME/pygobject/merge_requests/120
----
CC @MathieuDuponchelle
=> Fix handling of GValues containing a floating GObject

.travis.yml, src/source.rs
=> Implement FromGlib and ToGlib traits on Pid type

src/byte_array.rs
Just like the version of Vec, this does not actually initialize the
memory if the array has to grow and allows to get uninitialized memory.
The unit test actually caused valgrind warnings because of that.
Also extend unit test a bit.
----
CC @elmarco @GuillaumeGomez
=> Mark ByteArray::set_size() as unsafe

src/subclass/object.rs
See https://github.com/gtk-rs/glib/issues/518
=> Remove tests which panic in signals

src/value.rs, src/variant_type.rs
The constructor allows instantiating the error outside of the module, e.g. for use in an `assert_eq!`.
People might want to access the public fields when handling the error. Besides, if the error was implemented using an `enum`, the fields would be public.
Fixes https://github.com/gtk-rs/glib/issues/515
=> value::GetError: add a constructor and make fields public

src/checksum.rs, src/gstring.rs, src/translate.rs, src/value.rs, src/variant_type.rs
=> Implement Value::transform()

.travis.yml, Cargo.toml, src/lib.rs, src/main_context_futures.rs, src/source_futures.rs
And require Rust 1.39.
We can't use async/await in the tests/etc yet because that requires
switching to the 2018 edition, and that is blocked by
https://github.com/gtk-rs/gir/issues/746
=> Update to futures 0.3

src/clone.rs, tests/clone.rs
Fixes #532.
Fixes #533.
cc @sdroege @EPashkin @antoyo
=> Extend clone macro

src/boxed.rs, src/file_error.rs, src/main_context_futures.rs, src/object.rs, src/shared.rs, src/signal.rs, src/translate.rs, src/types.rs
With rustc 1.40.0, clippy checks that the `unsafe` functions come with
a `Safety` section. When running clippy on a downstream crate, the
macros such as `glib_wrapper!` leak the clippy warnings for the unsafe
functions.
Silence the warnings for now.
Fixes #538
=> Don't leak missing Safety doc clippy warnings (#538)

src/clone.rs, tests/clone.rs
I'll add the enforced fields renaming in the same PR. Running a few tests in the meantime. :)
=> Add renaming support

src/closure.rs, src/lib.rs, src/main_context_channel.rs, src/main_context_futures.rs, src/object.rs
After checking that the callback of the main context channel was always dropped from the correct thread, this check was actually failing often. I refactored the code now so that this can't happen anymore and we always ensure that non-Send values are only ever accessed from the correct thread.
Similar things happened with the GSource in the futures executor, which is also fixed and refactored now.
Overall the code should be much simpler now, and more correct!
=> API additions for connecting non-Send closures and thread-safety fixes to the main context channel and futures

src/source_futures.rs
The resulting Future/Stream will simply not be Send if the closure to
create it was not Send
=> Remove Send bound from SourceFuture/SourceStream

src/object.rs, src/subclass/guard.rs, src/subclass/types.rs
This way we can implement special cases more correctly:
- g_value_get_boxed() is invalid for GObjects
- Debug impl can print the actual type
- Only from_glib_none() will ever steal floating references and e.g.
cloning does not, see https://github.com/gtk-rs/glib/issues/545
After this the only places where we would steal floating references from
C code would be when explicitly calling from_glib_none() somewhere. That
is, when we call a function and get a (transfer none) reference to an
object back. (transfer floating) is an alias for this.
Especially, cloning and from_glib_borrow() would never steal floating
references, and because of this it is very important to only ever use
from_glib_borrow() inside callbacks, signal handlers and virtual method
trampolines.
----
@EPashkin …
=> Manually implement FFI code for GObject instead of using glib_shared_wrapper!

src/signal.rs, src/source.rs, src/translate.rs
These allows for some further optimizations.
Also do some minor cleanup of unused code.
=> Use NonZeroU64/32 for SignalHandlerId/SourceId

Cargo.toml, glib-macros/Cargo.toml, glib-macros/src/genum_derive.rs, glib-macros/src/lib.rs, glib-macros/tests/test.rs, src/lib.rs, src/subclass/mod.rs
This crate provides a proc derive macro implementing all the
boilerplate needed to define GEnum properties.
=> add genum-derive crate

src/object.rs, src/subclass/simple.rs
Especially for WeakRefs this is rather useful to have.
=> Derive fmt::Debug for a few more types

src/lib.rs, src/thread_pool.rs
Including a futures-enabled push function that allows to await on the
result of the closure passed to the thread pool:
let pool = glib::ThreadPool::new_shared(None)?;
let res = pool.push_future(|| calculate_things())?.await;
do_something_with_things(res);
=> Add glib::ThreadPool bindings

src/boxed.rs
The aim is to solve issue: 865 of the gir repository [865](https://github.com/gtk-rs/gir/issues/865)
AnyBox::Native(Box<T>) looks like the suitable variant for a fully owned *const T
Is checking non_null sufficient here before converting the raw pointer to a box?
I'm assuming here MM::copy() assures other type requirements are met.
Is this correct? 
While this solution makes my code compile and most of this impl is copied and adapted from other impls in the same file, there may well be things I have missed or misunderstood. Therefore a close look at what I've done is much appreciated.
=> Implements FromGlibPtrFull<*const T> for boxed types.

src/variant.rs
Bind Variant::new_from_bytes & Variant::get_data_as_bytes().
Related: #113.
=> Bind API to convert from/to bytes to/from Variant

src/quark.rs
When called more than once or for a quark that already exists otherwise,
we would always leak the string. Instead pass an unowned string to
g_quark_from_string().
----
CC @GuillaumeGomez @EPashkin
=> Don't pass an owned string to g_quark_from_static_string()

src/subclass/object.rs, src/subclass/types.rs
We don't know the exact memory layout of the Option<T> in relation to T
so can't easily go from a *const T to the surrounding *const Option<T>.
Since nightly from 2020-02-12 using both pointer types interchangeably
causes segmentation faults as their memory layouts are not actually
compatible and never were, but due to some compiler changes this
actually causes crashes at runtime now.
See https://github.com/rust-lang/rust/issues/69102 for details.
As an Option<_> was only used for some paranoid runtime checks that are
not really needed, simply store T directly as impl/private data of
subclasses.
This has the side-effect of having zero-sized impl/private data types to
actually occupy zero bytes of memory, and in some other cases to save a
few bytes of the allocation.
----
CC @EPashkin …
=> Don't store subclass impl/private data in an Option<T>

glib-macros/src/genum_derive.rs, glib-macros/tests/test.rs, src/subclass/object.rs, tests/clone.rs
=> Replace unwrap calls with expect in tests

src/subclass/types.rs
These can't be fulfilled in generic implementations quite often.
=> Don't require too strict bounds for ObjectSubclass::from_instance()

clone_tests/clone_compilation_errors.py, src/clone.rs
Fixes https://github.com/gtk-rs/glib/issues/597
=> Add clone test case for "async"

glib-macros/Cargo.toml, glib-macros/src/gboxed_derive.rs, glib-macros/src/genum_derive.rs, glib-macros/src/lib.rs, glib-macros/src/utils.rs, glib-macros/tests/test.rs, src/lib.rs, src/subclass/boxed.rs, src/subclass/mod.rs
Is there any reason to keep `glib_boxed_type!` and `glib_boxed_derive_traits!` or should I just in-lined them in the Derive macro?
=> glib-macros: add GBoxed derive

src/object.rs
Result<(), BoolError> is basically the same, just harder to use and
has_XXX() functions should return bools.
Fixes https://github.com/gtk-rs/glib/issues/608
=> Return a bool instead of a Result from Object::has_property()

src/clone.rs, src/lib.rs
Just one question: should we put it behind a feature instead?
=> Add print in case an upgrade failed

src/byte_array.rs, src/subclass/object.rs, src/value.rs
It makes the intentions clearer and potentially results in simpler
assembly, at least in debug builds.
=> Use mem::ManuallyDrop instead of mem::forget() everywhere

src/object.rs, src/source.rs, src/value.rs
I removed some `transmute` calls and added comments where they were missing.
=> Remove unnecessary transmute calls

src/error.rs, src/subclass/object.rs, src/value.rs
`std::error::Error::description` is deprecated since 1.42.0. Doc says
`Display` should be used instead. Current implementation for `Display`
on `BoolError` displays all the fields, which can be obtained via the
`Debug` derive.
This commit changes the `Display` impl on `BoolError` to match
previous impl for the `Error::description`. Tests can use
`to_string` in place of `description` for the same result.
Same for `glib::Error` and `value::GetError`.
Fixes https://github.com/gtk-rs/glib/issues/613
=> Remove deprecated Error::description impl

src/subclass/object.rs
With this new test alongside https://github.com/gtk-rs/gio/pull/289, we should prevent the mess we got recently to happen again. Next step: extra check on gir CI!
=> Add test for callbacks validity

src/quark.rs
Specifying it as 'static is very specific and instead we can let the
caller chose any lifetime they want here.
CC @GuillaumeGomez @EPashkin
=> Return a string of any lifetime from Quark::to_string()

.travis.yml, src/boxed.rs, src/byte_array.rs, src/checksum.rs, src/closure.rs, src/gstring.rs, src/log.rs, src/main_context.rs, src/main_context_channel.rs, src/main_context_futures.rs, src/object.rs, src/shared.rs, src/source_futures.rs, src/subclass/object.rs, src/subclass/types.rs, src/translate.rs, src/value.rs, src/variant.rs, src/variant_type.rs, tests/clone.rs
This adds CI enforcement of clippy and cleans up a lot of its unhappiness.
There are a number of places where I silence lints rather than solving them, and care will need to be taken to consider unsilencing and fixing them properly in the future, but this is sufficient for now.
=> Clippy cleanliness and CI enforcement

.travis.yml
It's effectively unmaintained at this point and bitrotten. There's no
point in testing it in the GLib CI until that is fixed, it fails to
build currently.
CC @EPashkin @GuillaumeGomez
=> Disable GTK4 from the Travis CI

Gir.toml, src/auto/functions.rs
It should be used by a StaticType impl, which we have, and not be
available as a standalone function.
----
CC @EPashkin @GuillaumeGomez
=> Ignore g_variant_get_gtype()

src/clone.rs, tests/clone.rs
When doing recursive calls in the macro, it calls itself by its raw name. This is a problem when importing and renaming it. This fix makes that possible.
=> Keep the scope of clone! macro arms in the crate

src/lib.rs, src/variant.rs
This PR will add container Variant API. It already adds basic array support.
=> Add container Variant API

src/variant.rs
Trying to port some code to the new variant API, this was causing errors.
I believe this is correct now.
=> fix: Do not transfer ownership in Variant::new_variant()

src/variant.rs
For consistency with rest of the API and Rust conventions.
Fixes #680.
=> Drop "new_" prefix from Variant constructor methods

src/lib.rs, src/variant.rs, src/variant_iter.rs
https://github.com/gtk-rs/glib/issues/682.
=> Add a VariantIter type, and Variant::iter() method

src/variant.rs, src/variant_dict.rs
This is useful when combined with the container variant functions and trait implementations from https://github.com/gtk-rs/glib/pull/651.
Implementing `ToVariant` would be useful as well, but isn't currently possible: https://github.com/gtk-rs/glib/issues/678
=> Implement FromVariant for Variant

src/source.rs, src/source_futures.rs
=> Use Duration instead of u32 when representing milliseconds

src/param_spec.rs
Regression from https://github.com/gtk-rs/glib/pull/688
cc: @sdroege
=> Fix for g_param_spec_types symbol linking error with MSVC

src/subclass/object.rs, src/subclass/types.rs
Also adds a call to `.get_instance()` to a test (which fails without the other change).
Fixes #701
=> Fix .get_instance() assert failure with zero-sized type

src/boxed.rs, src/object.rs, src/shared.rs, src/wrapper.rs
I believe this is more correct, and should allow more things to work without breaking anything. But it's hard to be sure with complicated macros...
This allows code like this to compile:
```rust
glib_wrapper! {
pub struct SimpleObject(
Object<(<SimpleObjectPrivate as ObjectSubclass>::Instance),
(<SimpleObjectPrivate as ObjectSubclass>::Class), SimpleObjectClass>)
@extends gtk::Widget;
match fn {
get_type => || SimpleObjectPrivate::get_type().to_glib(),
}
}
```
=> Use :ty rather than :path for ffi_name and ffi_class_name

src/object.rs, src/subclass/mod.rs, src/wrapper.rs
This makes it easier to define a wrapper for a type defined in Rust using `ObjectSubclass`. It also updates the `glib::subclass` documentation to use this.
I'm not all that fond of the `glib_wrapper!` macro, and would be happy to see something better, but this seems like a good way to improve subclassing ergonomics for now.
There's certainly more room for improvement in both the API and documentation for subclassing.
=> Add a ObjectSubclass version of glib_wrapper!

src/bridged_logging.rs, src/lib.rs
This adds a new `register_glib_to_logcrate_logger` function which routes all logging happening into glib to the log crate commonly used in Rust.
This is basically the reverse of `GlibLogger` (which routes the log crate to glib).
I found no trivial way (due to the fact that GlibLogger has a `const fn` constructor to simplify integration etc.) to prevent the user to use both `GlibLogger` and `register_glib_to_logcrate_logger` at the same time, which causes an obvious stack overflow (luckily, very early in the application lifetime). 
I clarified the potential stack overflow in the documentation. If preferred, different cargo features can be used to "xor" the two functionalities; I felt that to be more complicated than the problem it solved but it's personal opinion :)
Related issue: …
=> Added register_glib_to_logcrate_logger function to do glib-to-rust logging

src/object.rs, src/value.rs
I don't believe these any reason to use `PhantomData` in a struct like this that isn't generic.
`glib` itself, at least, still compiles and passes tests with this simply removed.
=> Remove PhantomData from struct created in glib_object_wrapper!

src/object.rs
Should fix https://github.com/gtk-rs/glib/pull/713/files#r511494658
By implementing it to invoke the traits on the wrapped `ObjectRef` the implementation shorter and clearer than before.
=> Don't derive PartialOrd/PartialEq implementations in glib_wrapper!

src/object.rs, src/subclass/types.rs, src/value.rs
The object might just be finalized, and in that case it's unsafe to access it and use any API on it. This can only happen from inside the Drop impl of Self.
=> Panic if ObjectSubclass::get_instance() is called on a finalizing object
